pipeline {
    agent any

    environment { 
        CHILD = 'INT2 Jenkins'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building int2..${env.MASTER}'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing int2..${env.CHILD}'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying int2....'
            }
        }
    }
}