pipeline {
    agent any

    environment { 
        CHILD = 'INT1 Jenkins'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building int1..${env.MASTER}'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing int1..${env.CHILD}'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying int1....'
            }
        }
    }
}